### ISSUE TITLE
ssh access by IP

### ISSUE THREAD

**Issue by extsoft** [ogerasymenko/pbc-PyBootCamp#1]
Seem `ssh vagrant@192.168.33.10` won't work. Am I right?
See 
https://github.com/ogerasymenko/PyBootCamp/blob/66f2d8fdc1cff3e4d4edcf48a2a4c6ce8c0ca612/day_1/Vagrantfile#L35

**Comment by ogerasymenko** [comment]
Fixed: uncomment line in config file.
