### ISSUE TITLE
VM name is not set

### ISSUE THREAD

**Issue by extsoft** [ogerasymenko/pbc-PyBootCamp#2]
According to [hw1](https://gist.github.com/extsoft/bf1b9884cbaccf1eb2efd0330ae542c7#1-vagrant) VM name has to be set in the section stated on 
https://github.com/ogerasymenko/pbc-PyBootCamp/blob/1a165b7d2c47f4a12b8327064f29345b277d0c5d/day_1/Vagrantfile#L52.

**Comment by ogerasymenko** [comment]
@extsoft Fixed.
